version: '3'
services:
  db:
    image: postgres
    volumes:
      - sample_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=swarmserver
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - PGDATA=/var/lib/postgresql/data

  server:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    links:
      - "db:sample_db"
volumes:
  sample_db: {}
